### PR TITLE
Rename filename to correct nomenclature

### PR DESCRIPTION
**Pull request by wendelfreitas**
Just fixing file name :heart:

### CODE REVIEW

**Comment by GLuchtenberg** [comment]
Shouldn't this filename be something like "page"? Connection reminds a database or server connection

**Comment by jaburcodes** [comment]
@wendelfreitas looks like now deployment failed

**Comment by jaburcodes** [comment]
@GLuchtenberg check: https://blog.apollographql.com/explaining-graphql-connections-c48b7c3d6976

**Comment by paulogdm** [comment]
Checking why.

**Comment by GLuchtenberg** [comment]
Ty jabur

**Comment by wendelfreitas** [comment]
@jaburcodes now is ok :smile:

**Pull request merged**
